apiVersion: meta.mpas.ocm.software/v1alpha1
kind: ProductDescription
metadata:
  name: weave-gitops
spec:
  description: Weave GitOps is a powerful extension to Flux, a leading GitOps engine and CNCF project. Weave GitOps provides insights into your application deployments, and makes continuous delivery with GitOps easier to adopt and scale across your teams.
  pipelines:
  - name: wego
    targetRoleName: ingress
    source:
      name: manifests
      version: 1.0.0
    localization:
      name: config
      version: 1.0.0
    configuration:
      rules:
        name: config
        version: 1.0.0
      readme:
        name: instructions
        version: 1.0.0
    validation:
      name: validation
      version: 1.0.0
  targetRoles:
  - name: ingress
    type: kubernetes
    selector:
      matchLabels:
        target.mpas.ocm.software/ingress-enabled: "true"
