# DON'T TOUCH IT, THIS WORKS!
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ocm-signing
spec:
  externalSecretName: "ocm-signing-es"
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["ocm-system", "mpas-system", "mpas-ocm-applications"]
  refreshTime: "10s"
  externalSecretSpec:
    secretStoreRef:
      name: secret-store-name
      kind: ClusterSecretStore
    refreshInterval: "10s"
    target:
      name: ocm-signing
    dataFrom:
    - extract:
        key: ocm-signing
      rewrite:
      - regexp:
          source: "(.*?)"
          target: "${1}"