# DON'T TOUCH IT, THIS WORKS!
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: ocm-dev-ca
spec:
  externalSecretName: "ocm-dev-ca-es"
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["ocm-system", "flux-system"]
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: secret-store-name
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: ocm-dev-ca
    dataFrom:
    - extract:
        key: ocm-dev-ca
      rewrite:
      - regexp:
          source: "(.*?)"
          target: "${1}"