apiVersion: mpas.ocm.software/v1alpha1
kind: ProductDeploymentGenerator
metadata:
  name: podinfo
  namespace: mpas-ocm-applications
spec:
  interval: 1m
  serviceAccountName: mpas-ocm-applications
  subscriptionRef:
    name: podinfo-subscription
    namespace: mpas-ocm-applications
