apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpas-ocm-applications
  namespace: mpas-system
imagePullSecrets:
- name: pull-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpas-ocm-applications
  namespace: mpas-ocm-applications
imagePullSecrets:
- name: pull-creds
