apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: mpas-gitea-receiver
  namespace: mpas-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: receiver-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: mpas-ocm-applications
